DROP DATABASE IF EXISTS AMA;
CREATE DATABASE IF NOT EXISTS AMA;

USE AMA;

CREATE TABLE T_AUTO_JOB (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  NAME_OF_JOB VARCHAR(255) NOT NULL,
  INTERVAL_BETWEEN_JOB SMALLINT UNSIGNED NOT NULL,
  DESCRIPTION TEXT,
  CREATE_DATE DATETIME NOT NULL,
  CREATOR_ID VARCHAR(16) NOT NULL,
  MODIFY_DATE DATETIME,
  MODIFIER_ID VARCHAR(16),
  ACTIVE_IND CHAR(1) NOT NULL DEFAULT 'Y'
);

DROP USER IF EXISTS ama_user@localhost;
CREATE USER IF NOT EXISTS ama_user@localhost identified by 'autojob';
GRANT SELECT,INSERT,UPDATE,DELETE ON AMA.* TO ama_user@localhost;

INSERT INTO T_AUTO_JOB (id, NAME_OF_JOB, INTERVAL_BETWEEN_JOB, CREATE_DATE, CREATOR_ID, ACTIVE_IND) VALUES (1, 'Check brakes', 6, now(), 'Diego_DLP', 'Y');
INSERT INTO T_AUTO_JOB (id, NAME_OF_JOB, INTERVAL_BETWEEN_JOB, CREATE_DATE, CREATOR_ID, ACTIVE_IND) VALUES (2, 'Check exterior running lights', 2, now(), 'Diego_DLP', 'Y');
INSERT INTO T_AUTO_JOB (id, NAME_OF_JOB, INTERVAL_BETWEEN_JOB, CREATE_DATE, CREATOR_ID, ACTIVE_IND) VALUES (3, 'Rotate Tires', 1, now(), 'Diego_DLP', 'Y');
