DROP DATABASE IF EXISTS AMA;
CREATE DATABASE IF NOT EXISTS AMA;

USE AMA;

CREATE TABLE T_AUTO_JOB (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  NAME_OF_JOB VARCHAR(50) NOT NULL,
  CREATE_DATE DATE
);

DROP USER IF EXISTS ama_user@localhost;
CREATE USER IF NOT EXISTS ama_user@localhost identified by 'autojob';
GRANT SELECT,INSERT,UPDATE,DELETE ON AMA.* TO ama_user@localhost;

INSERT INTO T_AUTO_JOB (id, NAME_OF_JOB) VALUES (1, 'Brake' );
INSERT INTO T_AUTO_JOB (id, NAME_OF_JOB) VALUES (2, 'Lights');
INSERT INTO T_AUTO_JOB (id, NAME_OF_JOB) VALUES (3, 'Tires');